name: publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          submodules: true
      - name: start postgresql server
        run: |
          sudo systemctl start postgresql.service
          sudo systemctl status postgresql.service
          pg_isready
          psql --version || true
          sudo -u postgres psql -c "ALTER USER ${{secrets.POSTGRES_USER}} PASSWORD '${{secrets.POSTGRES_PASSWORD}}';"
      - name: compile document
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_HOST: ${{secrets.POSTGRES_HOST}}
          POSTGRES_PORT: ${{secrets.POSTGRES_PORT}}
        run: |
          docker run --network host --rm \
            -e "POSTGRES_USER=$POSTGRES_USER" \
            -e "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" \
            -e "POSTGRES_HOST=$POSTGRES_HOST" \
            -e "POSTGRES_PORT=$POSTGRES_PORT" \
            -v "$HOME:$HOME" \
            -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" \
            -w "$GITHUB_WORKSPACE" \
            "ghcr.io/xu-cheng/texlive-full:latest" \
            /bin/bash -eo pipefail -c -- \
              "apk add cargo gcc linux-headers musl-dev postgresql16-client py3-pip python3 python3-dev rust && ./make.sh"
# deploy to github pages
      - name: deploy documentation
        uses: JamesIves/github-pages-deploy-action@94f3c658273cf92fb48ef99e5fbc02bd2dc642b2
        with:
          branch: gh-pages
          folder: /home/runner/work/databasesSlidesDE/databasesSlidesDE/website/
          single-commit: true
